### PR TITLE
Multiple file upload support

### PR DESCRIPTION
**Pull request by TellowKrinkle**
I feel a little bad about reintroducing `DiscordMessage.init(files: [DiscordFileUpload])` after removing it in 5.0.0, but it now actually does things with all the files!  (I realized this must be possible when I noticed the android client could do it)
This also includes a shim for the old `init(file: DiscordFileUpload?)` with a deprecated message so we can wait for a more major change to bump the major version number.

### CODE REVIEW

**Comment by nuclearace** [comment]
Have you tested these changes out? Like lone file, lone embed, file + embed?

**Comment by nuclearace** [comment]
Also I don't think you need a second init in this case. The other changes haven't been released yet.

**Comment by TellowKrinkle** [comment]
I didn't notice that the 5.0 PR hadn't been merged.
In that case, should I add a deprecated init for the old (`embeds: [DiscordEmbed]`) init so we can stay on 4.x until a bigger change (I would like to make some big changes to the audio system soon) or not?  It might also make the transition a little smoother since it'll warn anyone who updates with a custom message rather than just erroring.
Yeah I tested them.  You can even do this now: 
4 Custom Images

**Comment by nuclearace** [comment]
I don't care about version numbers, plus I've already made some changes to the audio system that warrants a major version change, but it probably would help to add a deprecated warning on it. 

If you plan on making audio changes, be forewarned, that's where I've spent the most amount of time on this library. Mostly to make it work for all systems, so you'll have to make sure that you don't break linux, macOS or iOS. You'll also need to make sure you don't increase the burden on the user. I also spent a lot of time trying to figure out a way that works at all. (You can look at the blame for those files to see all the pipes fiddling that was needed, mostly because of linux behavior with DispatchSources seemed to be shit.)

**Comment by TellowKrinkle** [comment]
All right.  I'll make sure to test on linux before I try to commit anything.  The main things I want to try are:
- Support for pull-based (callback-based) audio
- Not block a thread per audio playback

**Comment by nuclearace** [comment]
@tellowkrinkle Can you elaborate on your proposed changes on Discord? Because I'm not sure how feasible those goals would fit with how I designed the audio engine to be in the first place.

**Pull request merged**
