### PR TITLE
Update WebSocketKit to 2.1.0

### PR DESCRIPTION
**Pull request by fwcd**
Update the `WebSocketKit` dependency.

### CODE REVIEW

**Comment by TellowKrinkle** [comment]
Can we not require macOS 10.15 if possible?

Why does websocket-kit require it?

**Comment by fwcd** [comment]
@tellowkrinkle I don't know why they require it, the problem is that websocket-kit + SwiftDiscord won't build (at least when consumed as a library) without specifying the same minimum platform level.

You could file an issue on websocket-kit.

**Comment by nuclearace** [comment]
I think I’d be fine with this. @tellowkrinkle you see any issue?

**Comment by TellowKrinkle** [comment]
Yeah should be fine

**Pull request merged**
