### PR TITLE
Fix netsplit on sleep

### PR DESCRIPTION
**Pull request by TellowKrinkle**
Fixes an issue where the library would infinitely try to reconnect, causing things like [this](http://pastebin.ubuntu.com/25343435/)
This was caused by an issue with NSNumber allowing integers and booleans to be converted to each other

### CODE REVIEW

**Comment by nuclearace** [comment]
🤔 This raises my hmm alarm.

**Comment by nuclearace** [comment]
Usually when you see k* constants in a multi-platform project, something is not right.

**Comment by TellowKrinkle** [comment]
Aand I broke it on linux

**Comment by TellowKrinkle** [comment]
Looks like JSONSerialization imports Booleans as `Bool` on linux (rather than NSNumber)...

**Comment by nuclearace** [comment]
Yeah, anytime you see NSNumber or k* constants in multi-platform code, something is going on.

**Comment by nuclearace** [comment]
The reason for the difference is on Apple platforms, you aren't actually using open-source foundation, you're using Apple's, which is still backed by Objective-C fuckery.

**Comment by TellowKrinkle** [comment]
You apparently can't put an `#if` in a switch statement...

**Comment by nuclearace** [comment]
I still don't understand what causes the issue? Can you explain? I don't actually remember netsplit too much. I think it's only documented in the flowchart...

**Comment by TellowKrinkle** [comment]
Sure.  The issue that causes what's shown in the linked log message ([this](http://pastebin.ubuntu.com/25343435/)) starts if you put the computer running the bot to sleep.  It will time out on Discord's server (since it's asleep), but the bot will keep its local session ID.  When the computer is woken back up, it will receive a Code 9 Invalid Session from Gateway.

The Invalid Session packet is contains a boolean in the `"d"` field indicating whether or not the session is resumable.  The bot, if it detects that the boolean is set to true, is set to attempt a reconnect with the same Session ID, while printing `"Netsplit recieved, trying to resume"` (I don't actually know what netsplit is supposed to be, I just know that's what your logs will be filled with when the bug happens).  Otherwise, it clears the Session ID and tries to get a new one.

The first problem is that to check if it should try to keep the session or not the bot first attempts to unwrap the field as a boolean, and if it is, check if it's false.  If it was a boolean and false, it tries to get a new Session ID, otherwise it tries to reuse the current one.

The second problem is that when the DiscordGatewayPayloadData is created, it uses a `switch` statement that tries to cast the variable to a bunch of different types including both `Bool` and `Int`.  On Open Source Foundation, things imported from JSON are either of type `Bool` or `Int`, which aren't convertible to each other, but on OS X Foundation, they're both imported as `NSNumber`, which, being a C API, is perfectly happy to convert a `Bool` to a `1` or `0` `Int`, or a `1` or `0` `Int` to a `Bool`.  Because of this (and the order that the switch was in), the first switch case that succeeds is the `as Int`, which converts the boolean to an integer.

Because of this, when the bot tries to unwrap the value as a boolean, it fails (since the value was considered an integer), causing the bot to attempt to reuse its Session ID.  Unsurprisingly, it receives another Invalid Session from Gateway and keeps repeating this until it gets rate limited.

**Comment by nuclearace** [comment]
🤔 I'm still confused though. I remember them making changes to the internal NSNumber bridging to explicitly remember whether or not an NSNumber bridged from a bool.

**Comment by nuclearace** [comment]
Would it be possible to get the debug prints from when that happens? Because I can't reproduce. https://i.imgur.com/U45c7Ap.png

**Comment by nuclearace** [comment]
I do think the change to the logic is needed. If for whatever reason the case is wrong it shouldn't assume a netsplit.

I'm just not sure on the change to the switch statement...

**Comment by nuclearace** [comment]
And the test added passes with the old switch on macOS (Although the order of the new Linux one here fails when used on macOS)

**Comment by TellowKrinkle** [comment]
[Here's the debug log](https://pastebin.com/reqASRPf)

**Comment by nuclearace** [comment]
Was this Xcode 8.3.3 and Swift 3?

**Comment by nuclearace** [comment]
Would it be possible to keep the switch and keep the test and the if logic change so that a wrong case doesn't cause a netsplit. I want to get confirmation this isn't a regression in Apple's Foundation.

**Comment by nuclearace** [comment]
Alternatively we could just get rid of all that netsplit logic anyway. IIRC it's extremely unlikely to happen.

**Comment by TellowKrinkle** [comment]
Do you mean keep the switch as what it is in the main branch, and just add the netsplit if reorder and the test?

**Comment by nuclearace** [comment]
@tellowkrinkle Yeah. I want confirmation this isn't a regression.

**Comment by TellowKrinkle** [comment]
Let's see if this works.  [The two patches I removed for my future reference](https://gist.github.com/tellowkrinkle/4579e76bf44b65897b87a3c230e5cdc4)

**Comment by nuclearace** [comment]
fyi I opened https://bugs.swift.org/browse/SR-5863 for this. So far the reply says to reorder the cases in order of size... but that won't help if the int is 0 or 1.

**Pull request merged**
