### PR TITLE
Add support for MESSAGE_UPDATE event

### PR DESCRIPTION
**Pull request by neotron**
Useful for bot command handling since it allows editing of commands.

### CODE REVIEW

**Comment by neotron** [comment]
@nuclearace I'm converting my bot from my own library to this, and this is one feature I was missing. incredibly useful to listen to edits since it allows, well, fixing of typos without having to retype.

**Comment by neotron** [comment]
I see now the development branch greatly changes event handling to a cleaner delegate model.

I guess this could be considered out of date.

Although depends on schedule for that update?

**Comment by nuclearace** [comment]
I was planning on merging development soon. It'll bump the version up to 2, since trying to keep backwards compatibility between the callback system and the delegate system would just be a pain for no real benefit.

**Comment by nuclearace** [comment]
Closing since #7 cover this in the new system.

**Pull request closed without merging**
