### PR TITLE
Swift 5.1 compatibility

### PR DESCRIPTION
**Pull request by fwcd**
The networking-related classes from `Foundation` have recently been moved into a separate `FoundationNetworking` module (see also [here](https://forums.swift.org/t/foundationnetworking/24769) for discussion) and thus broken compatibility with Swift 5.1. Unfortunately, Vapor 2 also uses the old imports, thus we have to use Vapor 3 to build under Swift 5.1.

This PR merges the `development` branch and adds the required `FoundationNetworking` imports.

### CODE REVIEW

**Comment by nuclearace** [comment]
Thanks for looking it it. I haven't had a chance as I've been super busy with work

**Comment by fwcd** [comment]
The branch builds successfully, but the WebSocket connecting to Discord's gateway repeatedly closes.

Since the Vapor 2 version connects fine (using an older Swift version), I suspect there is something wrong with the new WebSocket implementation. Perhaps the HTTPClient tries to do non-persistent requests causing the WebSocket to immediately close every time Discord sends a response?

**Comment by fwcd** [comment]
I've reimplemented the WebSocket using Vapor 3's nio-websocket-client and this seems to work reasonably well, so I'm opening the PR for review/mergeability.

**Comment by nuclearace** [comment]
@fwcd Do you feel confident enough to open against the development branch? You'd be able to get CI going if you PR there.

I don't have time to check this second exactly what's changed. I think one of the last outstanding things that I was checking out was how to get voice working again in vapor 3. Is that something you wanted to checkout out as well?

**Comment by nuclearace** [comment]
This is great work btw, thanks for putting in the effort!

**Comment by fwcd** [comment]
I haven't really experimented with voice yet, though from what I can tell, the new voice implementation uses `BlueSocket` and should be unaffected be these changes. I'd be willing to take a look at that too, but can't promise when, currently.

For reference, [D2](https://github.com/fwcd/d2) is the Discord bot I'm working on and testing this with.

**Comment by nuclearace** [comment]
@fwcd no worries, I'll try and look at this sometime this week/weekend.

**Comment by TellowKrinkle** [comment]
BTW if you could add this change so libsodium gets found that would be helpful https://github.com/tellowkrinkle/SwiftDiscord/commit/14867c14e8c453e86417412f762cf06297f7c33b

**Comment by fwcd** [comment]
The websocket seems to reconnect unusually often (despite working fine):

```
2019-09-30 00:48:30.776 D2[14315:2dffb700] ERROR: DiscordEngine: Tried heartbeating on disconnected shard, shard: 0
2019-09-30 00:49:25.821 D2[14315:5a0d5700] LOG: DiscordWebSocketable: WebSocket closed, code: normalClosure, shard: 0;
2019-09-30 00:49:25.821 D2[14315:5a0d5700] LOG: DiscordEngine: Disconnected, shard: 0
2019-09-30 00:49:25.821 D2[14315:5a0d5700] LOG: DiscordEngine: Trying to resume gateway session on shard: 0
2019-09-30 00:49:25.823 D2[14315:5a0d5700] LOG: DiscordWebSocketable: WebSocket errored, uncleanShutdown, shard: 0
2019-09-30 00:49:25.823 D2[14315:5a0d5700] LOG: DiscordWebSocketable: Connecting to wss://gateway.discord.gg/?v=6&encoding=json, shard: 0
2019-09-30 00:49:25.823 D2[14315:5a0d5700] LOG: DiscordWebSocketable: Attaching WebSocket, shard: shard: 0
2019-09-30 00:49:26.342 D2[14315:5a0d5700] LOG: DiscordWebSocketable: Websocket connected, shard: shard: 0
2019-09-30 00:49:26.342 D2[14315:5a0d5700] LOG: DiscordEngine: Sending resume, shard: 0
2019-09-30 00:49:26.501 D2[14315:2dffb700] LOG: DiscordEngine: Resumed gateway session on shard: 0
2019-09-30 00:49:26.502 D2[14315:2dffb700] ERROR: DiscordEngine: Tried heartbeating on disconnected shard, shard: 0
2019-09-30 00:50:21.527 D2[14315:5a0d5700] LOG: DiscordWebSocketable: WebSocket closed, code: normalClosure, shard: 0;
2019-09-30 00:50:21.527 D2[14315:5a0d5700] LOG: DiscordEngine: Disconnected, shard: 0
2019-09-30 00:50:21.527 D2[14315:5a0d5700] LOG: DiscordEngine: Trying to resume gateway session on shard: 0
2019-09-30 00:50:21.529 D2[14315:5a0d5700] LOG: DiscordWebSocketable: WebSocket errored, uncleanShutdown, shard: 0
2019-09-30 00:50:21.529 D2[14315:5a0d5700] LOG: DiscordWebSocketable: Connecting to wss://gateway.discord.gg/?v=6&encoding=json, shard: 0
2019-09-30 00:50:21.529 D2[14315:5a0d5700] LOG: DiscordWebSocketable: Attaching WebSocket, shard: shard: 0
2019-09-30 00:50:22.041 D2[14315:5a0d5700] LOG: DiscordWebSocketable: Websocket connected, shard: shard: 0
2019-09-30 00:50:22.041 D2[14315:5a0d5700] LOG: DiscordEngine: Sending resume, shard: 0
2019-09-30 00:50:22.172 D2[14315:2dffb700] LOG: DiscordEngine: Resumed gateway session on shard: 0
2019-09-30 00:50:22.173 D2[14315:2dffb700] ERROR: DiscordEngine: Tried heartbeating on disconnected shard, shard: 0
```

Since these reconnects happen almost exactly once a minute, I suspect there is some timeout that causes the connection to close periodically.

**Comment by nuclearace** [comment]
Yeah that sounds like some issue I've seen before... although I think it'd been happening for a while.

**Pull request merged**
